import { register,login,logout,verfyEmail,verifyopt} from "../controlers/authControler.js";
import { verfytoken } from "../middlware/cookiesfunction.js";
import express from "express";
const router=express.Router();
router.post("/register",register);
router.post("/login",login);
router.post("/logout",logout);
router.post("/verifyopt",verfytoken,verifyopt);
router.post("/verifyemail",verfytoken,verfyEmail);
export default router;
